from geopy.geocoders import Nominatim
import csv

geolocator = Nominatim(user_agent="propftx")

locations = [
  "100 Feet Road",
  "AS Rao Nagar",
  "Abids Road",
  "Adibatla",
  "Alkapur Township",
  "Alwal",
  "Alwal Road",
  "Ameenpur",
  "Ameenpur Road",
  "Appa Junction Area",
  "Attapur",
  "Attapur Main Road",
  "Bachupally",
  "Bahadurpally",
  "Balaji Nagar Main Road",
  "Balanagar Main Road",
  "Bandlaguda Jagir",
  "Bandlaguda Jagir Road",
  "Banjara Hills",
  "Beeramguda Main Road",
  "Beeramguda Ramachandrapuram",
  "Begumpet",
  "Boduppal",
  "Bolarum",
  "Botanical Garden Road",
  "Bowrampet Road",
  "Chakripuram Road",
  "Chanda Nagar",
  "Dilsukhnagar",
  "Dr AS Rao Nagar Road",
  "Dulapally Cross Road",
  "ECIL Main Road",
  "East Anandbagh Main Road",
  "East Maredpally Road",
  "Financial District",
  "Gachibowli",
  "Gachibowli Kondapur Road",
  "Gachibowli Miyapur Road",
  "Gachibowli Road",
  "Gajularamaram",
  "Gandi Maisamma",
  "Gandipet",
  "Ghatkesar",
  "Gopanpalle",
  "Gundlapochampally",
  "HMDA Layout Road",
  "HUDA Layout Nalagandla",
  "Habsiguda Main Road",
  "Hafeezpet",
  "Hafeezpet Road",
  "Hanamkonda Hyderabad Road",
  "Hastinapuram",
  "Hi Tension Road",
  "Hill Country Road",
  "Himayat Nagar Road",
  "Himayatnagar",
  "Hitech City",
  "Hitech City Main Road",
  "Hitech City Road",
  "Hitex Road",
  "IDL Access Road",
  "ISB Road",
  "Isnapur",
  "Isnapur Indira Karan Road",
  "Izzathnagar",
  "JNTU Road",
  "Jeedimetla",
  "Jeedimetla Main Road",
  "Jubilee Hills",
  "Kalimandir Road",
  "Kanchi Gachibowli Road",
  "Kapra",
  "Kapra Main Road",
  "Kavadiguda",
  "Khajaguda",
  "Khajaguda Nanakramguda Road",
  "Kismatpur",
  "Kismatpur Road",
  "Kokapet",
  "Kollur",
  "Kompally",
  "Kondapur",
  "Kothaguda",
  "Kothapet",
  "Kowkoor Main Road",
  "Kukatpally",
  "Kukatpally Housing Board Colony",
  "Kukatpally Housing Board Road",
  "LB Nagar",
  "Lanco Hills Road",
  "Madeenaguda",
  "Madhapur",
  "Malkajgiri",
  "Mallampet",
  "Mallampet Road",
  "Mallapur",
  "Manchirevula",
  "Manikonda Jagir",
  "Manikonda Road",
  "Manjeera Pipeline Road",
  "Mansoorabad Road",
  "Marredpally",
  "Masjid Banda",
  "Medchal",
  "Medchal Road",
  "Mehdipatnam",
  "Mehdipatnam Road",
  "Military Dairy Farm Road",
  "Miyapur",
  "Miyapur Main Road",
  "Miyapur Road",
  "Mokila",
  "Moosapet",
  "Moti Nagar Erragadda",
  "Moula Ali",
  "Moula Ali Road",
  "Nacharam Mallapur Road",
  "Nagole",
  "Nagole Bandlaguda Road",
  "Nalagandla",
  "Nallagandla Tellapur Road",
  "Nanakaramguda",
  "Narsingi",
  "Narsingi Puppalaguda Main Road",
  "National Highway 65",
  "Nehru Outer Ring Road",
  "Neredmet Cross Road",
  "Nizampet",
  "Nizampet Miyapur Road",
  "Nizampet Road",
  "Osman Nagar",
  "Patancheru Chandanagar Road",
  "Patancheruvu",
  "Peerzadiguda",
  "Pocharam",
  "Power Welfare Society",
  "Pragathi Nagar",
  "Prgathi Nagar Road",
  "Puppalaguda",
  "Puppalaguda Road",
  "Quthbullapur",
  "Quthbullapur Main Road",
  "RTC Cross Road",
  "Raj Bhavan Road",
  "Rajendra Nagar Road",
  "Rajendranagar Mandal",
  "Ramachandrapuram",
  "Road Number 10",
  "SD Road",
  "Saidabad Colony Road",
  "Sainikpuri",
  "Saket Road",
  "Sanath Nagar",
  "Sangareddy",
  "Secundarabad",
  "Serilingampalle M",
  "Shaikpet",
  "Shaikpet Main Road",
  "Shaikpet Road",
  "Shamshabad",
  "Shankarpalli Hyderabad Road",
  "Shankarpalli Road",
  "Shastripuram Main Road",
  "Shivam Road",
  "Shivarampalli Village",
  "Shivarampally Jagir",
  "Somajiguda",
  "Srinagar Colony Main Road",
  "Suchitra",
  "Suchitra Road",
  "Tarnaka",
  "Tarnaka Main Road",
  "Tellapur",
  "Toli Chowki",
  "ToliChowki Road",
  "Trimulgherry ECIL Road",
  "Uppal",
  "Uppal Road",
  "Warangal Highway",
  "Yapral",
  "Yapral Main Road",
  "Yousufguda Main Road"
]



location_data = []

with open('geocoded_locations.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Location', 'Latitude', 'Longitude'])
    
    for location in locations:
        print(f"Geocoding location: {location}...")
        location_info = geolocator.geocode(location)
        
        if location_info:
            print(f"Found coordinates for {location}: Latitude = {location_info.latitude}, Longitude = {location_info.longitude}")
            location_data.append((location, location_info.latitude, location_info.longitude))
            writer.writerow([location, location_info.latitude, location_info.longitude])
        else:
            print(f"Could not find coordinates for {location}")
            location_data.append((location, None, None))
            writer.writerow([location, None, None])

print("\nGeocoding completed. Data saved to 'geocoded_locations.csv'.")
