import requests
import csv
import json

# Define the locations
locations = [
  "1 st Main Raod Narayanpura",
  "100 Feet Ring Road",
  "11th Main Road Malleshwaram",
  "Aga Abbas Ali Road",
  "Akshayanagar",
  "Ambalipura Sarjapur Road",
  "Amrutahalli",
  "Amruthahalli Main Road",
  "Anekal",
  "Anekal Main Road",
  "AnjanaPura",
  "Anjanapura Main Road",
  "Arekere",
  "Ashok Nagar",
  "Attibele",
  "Attibele Anekal Road",
  "Avalahalli",
  "BTM Layout",
  "Bagalur Colony",
  "Bagalur Main Road",
  "Bagaluru",
  "Balagere Road",
  "Banashankari",
  "Banaswadi",
  "Bangalore University Road",
  "Bannerghatta Anekal Road",
  "Bannerghatta Main Road",
  "Bannerughatta",
  "Basapaura Main Road",
  "Basavanagudi",
  "Battarahalli",
  "Begur",
  "Begur Koppa Road",
  "Begur Road",
  "Belathur Main Road",
  "Bellandur",
  "Bellary Road",
  "Bengaluru Kanakpura Road",
  "Benson Town",
  "Bhattarahalli",
  "Bhoganahalli Road",
  "Bhoganhalli",
  "Bilekahalli",
  "Binny Pete",
  "Block 1st Koramangala",
  "Block 9th Jayanagara",
  "Bommanahalli",
  "Bommanahalli Road",
  "Bommasandra",
  "Bommasandra Jigani Link Road",
  "Borewell Road",
  "Brookefield",
  "Budigere",
  "Budigere Cross",
  "Budigere Road",
  "Byatarayanapura",
  "CV Raman Nagar",
  "Cambridge Road",
  "Carmelaram",
  "Chandapura",
  "Chandapura Anekal Road",
  "Channasandra",
  "Channasandra Main road",
  "Chellikere",
  "Chikkakannalli",
  "Chokkanahalli",
  "Choodasandra",
  "Chunchgatta Main Road",
  "Church Street",
  "Coles Road",
  "Commissariat Road",
  "Cooke Town",
  "Cox Town",
  "Cunningham Road",
  "Dasarahalli Main Road",
  "Davis Road",
  "Devanahalli",
  "Devarachikkanahalli Road",
  "Devasthanagalu",
  "Doddaballapur Main Road",
  "Doddaballapura Main Road",
  "Doddagubbi Main Road",
  "Doddakallasandra",
  "Doddakannelli",
  "Doddakannelli Chikkanayakana Halli Road",
  "Doddanekundi",
  "Dollars Colony stage 2nd RMV",
  "Domlur",
  "Dommasandra",
  "Double Road",
  "Dr Rajkumar Road",
  "ECC Road",
  "EPIP Zone",
  "Electronic City",
  "GKVK Road",
  "Gatthalli Road",
  "Gear School Road",
  "Gottigere",
  "Gottigere Main Road",
  "Gubbalala",
  "Gubbalala Main Road",
  "Gunjur",
  "Gunjur Balagere Road",
  "HAL Old Airport Road",
  "HBR Layout",
  "HSR Layout",
  "Hadosiddapura",
  "Hagadur Main Road",
  "Halasuru",
  "Haralur",
  "Haralur Main Road",
  "Hebbal",
  "Hebbal Kempapura",
  "Hennur Bagalur Main Road",
  "Hennur Bande",
  "Hennur Gardens",
  "Hennur Main Road",
  "Hesarghatta Road",
  "Holiday Village Road",
  "Hoodi",
  "Hoodi Main Road",
  "Horamavu",
  "Horamavu Agara",
  "Horamavu Agara Main Road",
  "Horamavu Main Road",
  "Hormavu Agara",
  "Hosa Road",
  "Hosa Road Area",
  "Hosabasavanapura",
  "Hosakerehalli",
  "Hoskote",
  "Hoskote Chintamani Road",
  "Hosur Main Road",
  "Hosur Road",
  "Hulimavu",
  "Huskur Road",
  "Hutchins Road",
  "ITPL",
  "Immadihalli",
  "Indiranagar",
  "JCR Layout",
  "JP Nagar",
  "Jakkur",
  "Jakkur Road",
  "Jakkuru Layout",
  "Jalahalli",
  "Jalahalli West",
  "Jayanagar",
  "Jigani",
  "Jigani Road",
  "Judicial Layout",
  "Kadubeesanahalli",
  "Kadubeesanahalli Road",
  "Kadugodi",
  "Kaggadasapura",
  "Kaikondrahalli",
  "Kalena Agrahara",
  "Kalkere",
  "Kalkere Main Road",
  "Kalyan Nagar",
  "Kammanahalli",
  "Kammasandra Electronic City",
  "Kanakapura",
  "Kanakapura Road",
  "Kannamangala",
  "Kannamangala Main Road",
  "Kasavanahalli",
  "Kasavanahalli Main Road",
  "Kathriguppe Main Road",
  "Kempegowda International Airport Road",
  "Kengeri",
  "Kengeri Satellite Town",
  "Kodathi",
  "Kodichikkanahalli Main Road",
  "Kogilu",
  "Konanakunte",
  "Koramangala",
  "Kothanur",
  "Krishnarajapura",
  "Kudlu",
  "Kudlu Gate",
  "Kudlu Main Road",
  "Kumaraswamy Layout",
  "Kundalahalli",
  "Lalbagh Main Road",
  "Langford Road",
  "MSR College Road",
  "Magadi Chord Road",
  "Magadi Main Road",
  "Mahadevapura",
  "Mahatma Gandhi Road",
  "Malleshwaram",
  "Manayata Tech Park",
  "Manyata Tech Park Road",
  "Marathahalli",
  "Marathahalli Main Road",
  "Marathahalli Sarjapur Outer Ring Road",
  "MedaHalli",
  "Medahalli Kadugodi Road",
  "Medahalli Main Road",
  "Millers Road",
  "Museum Road",
  "Mysore Road",
  "NRI Layout Main Road",
  "Naagarabhaavi",
  "Nagarabhavi Main Road",
  "Nagasandra",
  "Nagavara",
  "Nallurhalli",
  "Nandi Durga Road",
  "Neeladri Road",
  "Neotown Road",
  "New Airport Road",
  "New BEL Road",
  "Nice Ring Road",
  "OMBR Layout",
  "Old Madras Road",
  "Outer Ring Road",
  "Padmanabhanagar",
  "Panathur",
  "Panathur Main Road",
  "Pattandur Agrahara",
  "Peenya",
  "Phase 1 Electronics City",
  "Phase 2 Electronic City",
  "Phase 2nd Judicial Layout",
  "Phase 5 JP Nagar",
  "Phase 6 JP nagar",
  "Phase 7 JP Nagar",
  "Phase 8th JP Nagar",
  "Pulikeshi Nagar",
  "Queens Road",
  "RK Hegde Nagar",
  "RR Nagar",
  "RT Nagar",
  "Rachenahalli",
  "Rachenahalli Main Road",
  "Rajajinagar",
  "Ramagondanahalli Whitefield",
  "Ramamurthy Nagar",
  "Rashtriya Vidyalaya Road",
  "Rayasandra",
  "Rayasandra Main Road",
  "Richards Town",
  "Richmond Road",
  "Richmond Town",
  "Sadarmangala Main Road",
  "Sahakar Nagar",
  "Saint Johns Road",
  "Sampige Road",
  "Sanjay Nagar Main Road",
  "Sanjayanagara",
  "Sankey Road",
  "Sarjapur Road",
  "Sarjapura",
  "Sarjapura Attibele Road",
  "Seegehalli",
  "Seegehalli Krishnarajapura",
  "Seegehalli Road",
  "Silver County Road",
  "Singasandra",
  "Somasundarapalya Main Road",
  "Sompura",
  "Soukya Road",
  "Spencer Road",
  "Stage 2 RMV",
  "Stage 2nd BTM Layout",
  "Stage 3rd Banashankari",
  "Stage 6th Banashankari",
  "State Highway 35",
  "Subramanyapura",
  "Subramanyapura Main Road",
  "Talaghattapura",
  "Thalaghattapura Main Road",
  "Thambu Chetty Palya",
  "Thambu Chetty Palya Main Road",
  "Thanisandra",
  "Thanisandra Main Road",
  "Thimmaiah Road",
  "Thubarahalli",
  "Thurahalli",
  "Tumkur Road",
  "Ulsoor Road",
  "Uttarahalli Hobli",
  "Uttarahalli Main Road",
  "Vajarahalli",
  "Varthur",
  "Varthur Lake Road",
  "Varthur Road",
  "Vasanth Nagar",
  "Vidyaranyapura",
  "Vidyaranyapura Main Road",
  "Vijaynagar",
  "Vijaynagar Main Road",
  "Vittal Mallya Road",
  "Viviani Road",
  "Whitefield",
  "Whitefield Hoskote Road",
  "Whitefield Main Road",
  "Yelachenahalli",
  "Yelahanka",
  "Yelahanka Airforce Base",
  "Yelahanka New Town",
  "Yelahanka Road",
  "Yeswanthpur"
]


quarters = ["Jan-Mar", "Apr-Jun", "Jul-Sep", "Oct-Dec"]
years = list(range(2024, 2031))  

api_url = " https://ai-ml-propftx.letsphoenix.com/predict"

headers = {
    'Content-Type': 'application/json'
}

def get_price_data_for_location(location, quarters, years):
    predictions = [{"location": location, "quarter": quarter, "year": year} for year in years for quarter in quarters]
    payload = {
        "predictions": predictions,
        "city": "Bangalore",  
        "priceType": "all" 
    }
    
    response = requests.post(api_url, headers=headers, data=json.dumps(payload))
    
    if response.status_code == 200:
        try:
            result = response.json()
            if isinstance(result, list):  # Check if the result is a list of predictions
                return result
            else:
                print(f"Error in API response: {result}")
                return None
        except Exception as e:
            print(f"Failed to parse JSON response: {e}")
            return None
    else:
        print(f"API call failed with status code {response.status_code}: {response.text}")
        return None

csv_filename = "bangalore_predicted_prices.csv"

with open(csv_filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["location", "quarter", "year", "min_price", "max_price", "avg_price"])

    for location in locations:
        print(f"Fetching data for {location}...")
        result = get_price_data_for_location(location, quarters, years)
        
        if result is None:
            print(f"Failed to fetch data for {location}. Skipping...")
        elif 'error' in result:
            print(f"API returned error for {location}: {result['error']}")
        else:
            print(f"Data successfully fetched for {location}. Writing to CSV...")
            for prediction in result:
                location = prediction.get('location')
                quarter = prediction.get('quarter')
                year = prediction.get('year')
                min_price = prediction.get('min_price', 'N/A')
                max_price = prediction.get('max_price', 'N/A')
                avg_price = prediction.get('avg_price', 'N/A')

                writer.writerow([location, quarter, year, min_price, max_price, avg_price])

print(f"Data processing complete. Results saved to {csv_filename}")
