import requests
import csv
import logging

logging.basicConfig(level=logging.INFO, format='%(message)s')

locations = [
  "100 Feet Anand Nagar Road",
  "100 Feet Road",
  "100 Feet Road",
  "120 Feet Ring Road",
  "132 Feet Ring Road",
  "Aarohi Club Road",
  "Airport Road",
  "Ambawadi",
  "Ambawadi",
  "Ambli",
  "Ambli",
  "Ambli Bopal Road",
  "Ambli Bopal Road",
  "Ambli Road",
  "Ambli Road",
  "Anand Nagar Prahlad Nagar",
  "Anand Nagar Prahlad Nagar",
  "Ashram Road",
  "Ashram Road",
  "Ashram Road Area",
  "Balol Nagar Cross Road",
  "Bhadaj",
  "Boakdev",
  "Bodakdev",
  "Bopal",
  "Bopal",
  "Bopal Ghuma Road",
  "Bopal Road",
  "Chanakyapuri",
  "Chandkheda",
  "Chandlodiya",
  "Chandlodiya Road",
  "Chenpur Road",
  "Chharodi",
  "Chharodi",
  "Chimanlal Girdharlal Road",
  "Chimanlal Girdharlal Road",
  "Corporate Road",
  "Corporate Road",
  "Daskroi",
  "Daxini Society",
  "Dev Kutir 1",
  "Devnagar",
  "Drive In Road",
  "Drive In Road",
  "Ellisbridge",
  "Friends Colony Bodakdev",
  "Friends Colony Bodakdev",
  "Gala Gymkhana Road",
  "Gala Gymkhana Road",
  "Ghatlodiya",
  "Ghodasar",
  "Ghuma",
  "Ghuma Road",
  "Godhavi",
  "Gota",
  "Gota",
  "Gota Gam",
  "Gulbai Tekra",
  "Gurukul",
  "Hebatpur",
  "Iscon Ambli Road",
  "Iscon Ambli Road",
  "Jagatpur",
  "Jagatpur",
  "Jagatpur Road",
  "Jagatpur Road",
  "Jagatpur Village",
  "Jain Nagar Ghuma",
  "Jodhpur Gam Road",
  "Jodhpur Gam Road",
  "Jodhpur Village",
  "Jodhpur Village Road",
  "Judges Bunglow Road",
  "Judges Bunglow Road",
  "Kathwada Road",
  "Khodiyar",
  "Khokhra",
  "Koteshwar",
  "Koteshwar Mandir Road",
  "Makarba",
  "Makarba",
  "Makarba Road",
  "Maninagar",
  "Maninagar Road",
  "Memnagar",
  "Motera",
  "Motera Koteshwar Road",
  "Motera Road",
  "Motera Stadium Road",
  "Naranpura",
  "Naroda",
  "Naroda Dehgam Road",
  "Naroda Road",
  "Narol Road",
  "Narol Vatva Road",
  "Narolgam",
  "Nava Naroda",
  "Nava Vadaj",
  "Navrangpura",
  "Navrangpura",
  "Nehru Nagar Ambawadi",
  "Nehru Nagar Ambawadi",
  "New CG Road",
  "New Ranip",
  "New Vatva Road",
  "Nikol",
  "Nikol Gam Road",
  "Nikol Naroda Road",
  "North Bopal Road",
  "NR Vandematram Cross Road",
  "NR Vandematram Cross Road",
  "Nyay Marg",
  "Nyay Marg",
  "Ognaj",
  "Ognaj Gota Road",
  "Paldi",
  "Paldi Road",
  "Prahlad Nagar",
  "Prahlad Nagar",
  "Prematirth Derasar Road",
  "Prernatirth Derasar Road",
  "Rajpath Rangoli Road",
  "Rajpath Rangoli Road",
  "Ramdev Nagar",
  "Ramdevnagar Road",
  "Rampura Road",
  "Ranip",
  "Sanand",
  "Sanand Nalsarovar Road",
  "Sanand Sarkhej Road",
  "Sanand Sarkhej Road",
  "Sanand Viramgam Highway",
  "Sanathal",
  "Sardar Patel Ring Road",
  "Sardar Patel Ring Road",
  "Sarkhej",
  "Sarkhej Ahmedabad Main Road",
  "Sarkhej Gandhinagar Highway",
  "Sarkhej Gandhinagar Highway",
  "Sarkhej Okef",
  "Satellite",
  "Satellite",
  "Satellite Road",
  "Satellite Road",
  "Satya Marg",
  "Science City",
  "Science City",
  "Science City Road",
  "Science City Road",
  "Sector 7 South Bopal",
  "Shahibag",
  "Shantigram",
  "Shantigram Road",
  "Shantipura Circle",
  "Shayamal Cross Road",
  "Shela",
  "Shilaj",
  "Shilaj Ambli",
  "Shivranjani Cross Road",
  "Shivranjani Cross Road",
  "Shyamal",
  "Shyamal Cross Road",
  "Sindhu Bhavan Marg",
  "Sindhu Bhavan Marg",
  "Sola",
  "Sola Road",
  "Sola Road",
  "South Bopal",
  "South Bopal",
  "Thaltej",
  "Thaltej",
  "Thaltej Shilaj Road",
  "Thaltej Shilaj Road",
  "Tragad Road",
  "Tragad Road",
  "Ullaria Road",
  "Umiya Dham Road",
  "University Road",
  "Usmanpura",
  "Vaishnodevi Circle",
  "Vaishnodevi Circle",
  "Vandematram Arcade",
  "Vasna",
  "Vastral",
  "Vastral Road",
  "Vastrapur",
  "Vastrapur",
  "Vatva",
  "Vejalpur",
  "Vejalpur Road",
  "Vijay Cross Road",
  "Vijay Cross Road",
  "Zalod Ahmedabad Highway",
  "Zundal"
]

 
quarters = ["Jan-Mar", "Apr-Jun", "Jul-Sep", "Oct-Dec"]

years = list(range(2024, 2031))

csv_header = ["location", "year", "quarter", "avg_price", "max_price", "min_price"]

with open('Bangalore_recommedation_price_predictions1.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(csv_header)

    for location in locations:
        for year in years:
            predictions = [{"location": location, "quarter": quarter, "year": year} for quarter in quarters]
            
            payload = {
                "predictions": predictions,
                "city": "Ahmedabad",
                "priceType": "all"
            }

            try:
                logging.info(f"Fetching data for {location} - {year}")
                response = requests.post("https://ai-ml-propftx.letsphoenix.com/predict", json=payload)
                
                if response.status_code == 200:
                    data = response.json()

                    for entry in data:
                        row = [
                            entry["location"],
                            entry["year"],
                            entry["quarter"],
                            entry["avg_price"],
                            entry["max_price"],
                            entry["min_price"]
                        ]
                        writer.writerow(row)  
                        logging.info(f"Data saved for {location} - {year} - {entry['quarter']}")

                else:
                    logging.error(f"Failed to fetch data for {location} - {year}: {response.status_code}")
            
            except Exception as e:
                logging.error(f"Error occurred while fetching data for {location} - {year}: {str(e)}")
